### ISSUE TITLE
:bug: Don't leak DataType objects

### ISSUE THREAD

**Issue by jdeans289** [jdeans289/icg2#21]
Currently, I think we're leaking memory all over the place. The DataTypes are a particular culprit of this. My original plan was just to have the TypeDictionary own the types, and just let everyone else have a pointer to something in there. The addition of ModifierTypes, which don't exist in the type dictionary, and are created for each type that uses them as a subtype, violates this. 

Possible solutions:
- smart pointers
    - this seems like a pretty good use case for shared_ptr. However, this might cause problems with other Trick dependencies down the line, ie SWIG, and I'm not really sure if we are going to cut off part of our user base that is stuck on older compilers. We would definitely be stuck on c++11 features only, which restricts some smart pointer features that are pretty standard elsewhere. Plus, no one else on Trick knows what a smart pointer is.

- DataTypes own their subtype
    - DataTypeInator **always** returns a new copy of whatever type it resolves to. I would love to just return by value, but subtype polymorphism is tightly coupled to dynamic allocation in c++ so no. Going to have to take advantage of clone()
    - Will have to adjust all the rule of 5 to deal with this
 
No matter which approach we choose, DataTypeInator->resolve() needs to return something consistent memory-management wise. Currently, if the result is a base type, it returns a pointer to the BaseType in the map. Otherwise, it allocates a new ModifierType and returns that. This seems like a great situation for shared_ptr, but I predict that the limitations stated above will make that practically difficult on this team. I think option 2 is probably better.

**Comment by Mrockwell2** [comment]
Not sure if this should be a separate issue, but it is a memory leak thing. 
[`What happens to old LOCAL Allocs?`](https://github.com/jdeans289/icg2/blob/aad7ec8e8f7f9bf1c8214a8f56a8bf46add223de/DataTypes/src/MemoryManagement/MemoryManager.cpp#L203C1-L203C1)

**Comment by jdeans289** [comment]
Let's open a separate issue for that, I'll rename this one to something more appropriate. Thanks Marcus!
